spring.application.name=WeeklyAssessment2
spring.datasource.url=jdbc:postgresql://localhost:5432/AssessmentsDB
spring.datasource.username=postgres
spring.datasource.password=TIGER

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081